//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverQuestDPSPlugin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EverQuestDPSPluginResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EverQuestDPSPluginResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverQuestDPSPlugin.Resources.EverQuestDPSPluginResource", typeof(EverQuestDPSPluginResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to throw|pierce|gore|crush|slash|hit|kick|slam|bash|shoot|strike|bite|grab|punch|scratch|rake|swipe|claw|maul|smash.
        /// </summary>
        internal static string attackTypes {
            get {
                return ResourceManager.GetString("attackTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crippling Blow.
        /// </summary>
        internal static string CripplingBlow {
            get {
                return ResourceManager.GetString("CripplingBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to damageSpecial.
        /// </summary>
        internal static string DamageSpecial {
            get {
                return ResourceManager.GetString("DamageSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Bow Shot.
        /// </summary>
        internal static string DoubleBowShot {
            get {
                return ResourceManager.GetString("DoubleBowShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block(|s)|dodge(|s)|parr(ies|y)|riposte(|s).
        /// </summary>
        internal static string evasionTypes {
            get {
                return ResourceManager.GetString("evasionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing Blow.
        /// </summary>
        internal static string FinishingBlow {
            get {
                return ResourceManager.GetString("FinishingBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flurry.
        /// </summary>
        internal static string Flurry {
            get {
                return ResourceManager.GetString("Flurry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky.
        /// </summary>
        internal static string Lucky {
            get {
                return ResourceManager.GetString("Lucky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EverQuest Damage Per Second Parser.
        /// </summary>
        internal static string pluginName {
            get {
                return ResourceManager.GetString("pluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `s pet.
        /// </summary>
        internal static string possessivePetString {
            get {
                return ResourceManager.GetString("possessivePetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riposte.
        /// </summary>
        internal static string Riposte {
            get {
                return ResourceManager.GetString("Riposte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        internal static string Strikethrough {
            get {
                return ResourceManager.GetString("Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twincast.
        /// </summary>
        internal static string Twincast {
            get {
                return ResourceManager.GetString("Twincast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild Rampage.
        /// </summary>
        internal static string WildRampage {
            get {
                return ResourceManager.GetString("WildRampage", resourceCulture);
            }
        }
    }
}
