//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverQuestDPS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GenericObjects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericObjects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverQuestDPS.Properties.GenericObjects", typeof(GenericObjects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backstab|throw|pierce|gore|crush|slash|hit|kick|slam|bash|shoot|strike|bite|grab|punch|scratch|rake|swipe|claw|maul|smash|frenzies on|frenzy.
        /// </summary>
        internal static string attackTypes {
            get {
                return ResourceManager.GetString("attackTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crippling Blow.
        /// </summary>
        internal static string CripplingBlow {
            get {
                return ResourceManager.GetString("CripplingBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        internal static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string cultureSetting {
            get {
                return ResourceManager.GetString("cultureSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to damageSpecial.
        /// </summary>
        internal static string DamageSpecial {
            get {
                return ResourceManager.GetString("DamageSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dateTimeOfLogLine.
        /// </summary>
        internal static string dateTimeOfLogLine {
            get {
                return ResourceManager.GetString("dateTimeOfLogLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Bow Shot.
        /// </summary>
        internal static string DoubleBowShot {
            get {
                return ResourceManager.GetString("DoubleBowShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd MMM dd HH:mm:ss yyyy.
        /// </summary>
        internal static string eqDateTimeStampFormat {
            get {
                return ResourceManager.GetString("eqDateTimeStampFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to familiar.
        /// </summary>
        internal static string familiar {
            get {
                return ResourceManager.GetString("familiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing Blow.
        /// </summary>
        internal static string FinishingBlow {
            get {
                return ResourceManager.GetString("FinishingBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flurry.
        /// </summary>
        internal static string Flurry {
            get {
                return ResourceManager.GetString("Flurry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming.
        /// </summary>
        internal static string IncomingTag {
            get {
                return ResourceManager.GetString("IncomingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eqlog_*.txt.
        /// </summary>
        internal static string logFilter {
            get {
                return ResourceManager.GetString("logFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucky.
        /// </summary>
        internal static string Lucky {
            get {
                return ResourceManager.GetString("Lucky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse over user interface element to get description.
        /// </summary>
        internal static string MouseLeave {
            get {
                return ResourceManager.GetString("MouseLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string OutgoingPositiveAlly {
            get {
                return ResourceManager.GetString("OutgoingPositiveAlly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing.
        /// </summary>
        internal static string OutgoingTag {
            get {
                return ResourceManager.GetString("OutgoingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pet.
        /// </summary>
        internal static string pet {
            get {
                return ResourceManager.GetString("pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Exited.
        /// </summary>
        internal static string pluginExited {
            get {
                return ResourceManager.GetString("pluginExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EverQuest Damage Per Second Parser.
        /// </summary>
        internal static string pluginName {
            get {
                return ResourceManager.GetString("pluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Started.
        /// </summary>
        internal static string pluginStarted {
            get {
                return ResourceManager.GetString("pluginStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to possesiveOf.
        /// </summary>
        internal static string possesiveOf {
            get {
                return ResourceManager.GetString("possesiveOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaidRoster_*-*-*.txt.
        /// </summary>
        internal static string RaidRosterPath {
            get {
                return ResourceManager.GetString("RaidRosterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riposte.
        /// </summary>
        internal static string Riposte {
            get {
                return ResourceManager.GetString("Riposte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secondaryPossesiveOf.
        /// </summary>
        internal static string secondaryPossesiveOf {
            get {
                return ResourceManager.GetString("secondaryPossesiveOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specialAttackTerm-none.
        /// </summary>
        internal static string specialAttackNoneLocalization {
            get {
                return ResourceManager.GetString("specialAttackNoneLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialString.
        /// </summary>
        internal static string SpecialStringTag {
            get {
                return ResourceManager.GetString("SpecialStringTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        internal static string Strikethrough {
            get {
                return ResourceManager.GetString("Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twincast.
        /// </summary>
        internal static string Twincast {
            get {
                return ResourceManager.GetString("Twincast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ward.
        /// </summary>
        internal static string ward {
            get {
                return ResourceManager.GetString("ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warder.
        /// </summary>
        internal static string warder {
            get {
                return ResourceManager.GetString("warder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild Rampage.
        /// </summary>
        internal static string WildRampage {
            get {
                return ResourceManager.GetString("WildRampage", resourceCulture);
            }
        }
    }
}
